//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace IQSDirectory {
    
    
    public partial class CompanyProfile {
        
        /// <summary>
        /// copropageemail control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::IQSDirectory.Controls.copro_page_email copropageemail;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new IQSDirectory.SiteMaster Master {
            get {
                return ((IQSDirectory.SiteMaster)(base.Master));
            }
        }
    }
}
